<a href="https://colab.research.google.com/github/ajits-github/Machine_Learning_In_Bioinformatics/blob/main/Machine_Learning_in_Bioinformatics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###MethylDataWithDbgapId DataFrame

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:

file_path = "/content/metRmOlWithDbgapId.txt"
df_methyl = pd.read_csv(file_path, sep='\t', index_col=0)
# df_methyl = df_methyl.T
# print(df_methyl)
df_methyl.head()

,34,35,37,39,40,41,44,46,52,53,...,14,18,19,269,24,25,26,27,28,31
dbGapSubjctId,,,,,,,,,,,,,,,,,,,,,
cg26211698,0.018852,0.023741,0.023376,0.037224,0.018712,0.025110,0.015484,0.021162,0.020475,0.026372,...,0.022684,0.021980,0.022296,0.025086,0.018492,0.019187,0.025315,0.023315,0.019223,0.018230
cg03790787,0.068036,0.081941,0.103914,0.051119,0.104110,0.088810,0.081404,0.076911,0.062057,0.081126,...,0.057089,0.081262,0.118663,0.082806,0.086863,0.078102,0.090376,0.104590,0.079274,0.083737
cg04672450,0.009639,0.013243,0.010931,0.022289,0.012151,0.013536,0.016800,0.013280,0.013590,0.007595,...,0.009227,0.011758,0.009513,0.009652,0.009818,0.009355,0.008954,0.013901,0.007831,0.015042
cg14324200,0.204592,0.064252,0.133139,0.059606,0.092799,0.113580,0.094694,0.166240,0.158260,0.175960,...,0.108734,0.121616,0.181430,0.104992,0.156035,0.196719,0.112995,0.112599,0.147677,0.157535
cg04485075,0.010062,0.015012,0.012881,0.047412,0.017496,0.022166,0.014335,0.011306,0.011356,0.013433,...,0.013298,0.015789,0.012658,0.019463,0.016777,0.013480,0.011508,0.014426,0.014793,0.013828

In [ ]:
df_methyl

,34,35,37,39,40,41,44,46,52,53,...,14,18,19,269,24,25,26,27,28,31
dbGapSubjctId,,,,,,,,,,,,,,,,,,,,,
cg26211698,0.018852,0.023741,0.023376,0.037224,0.018712,0.025110,0.015484,0.021162,0.020475,0.026372,...,0.022684,0.021980,0.022296,0.025086,0.018492,0.019187,0.025315,0.023315,0.019223,0.018230
cg03790787,0.068036,0.081941,0.103914,0.051119,0.104110,0.088810,0.081404,0.076911,0.062057,0.081126,...,0.057089,0.081262,0.118663,0.082806,0.086863,0.078102,0.090376,0.104590,0.079274,0.083737
cg04672450,0.009639,0.013243,0.010931,0.022289,0.012151,0.013536,0.016800,0.013280,0.013590,0.007595,...,0.009227,0.011758,0.009513,0.009652,0.009818,0.009355,0.008954,0.013901,0.007831,0.015042
cg14324200,0.204592,0.064252,0.133139,0.059606,0.092799,0.113580,0.094694,0.166240,0.158260,0.175960,...,0.108734,0.121616,0.181430,0.104992,0.156035,0.196719,0.112995,0.112599,0.147677,0.157535
cg04485075,0.010062,0.015012,0.012881,0.047412,0.017496,0.022166,0.014335,0.011306,0.011356,0.013433,...,0.013298,0.015789,0.012658,0.019463,0.016777,0.013480,0.011508,0.014426,0.014793,0.013828
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg22415432,0.036936,0.039335,0.038415,0.011352,0.038588,0.035204,0.059946,0.032939,0.038712,0.035260,...,0.027126,0.038100,0.026386,0.036874,0.036575,0.038281,0.033395,0.039843,0.029094,0.045354
cg20401549,0.041803,0.296774,0.312115,0.300000,0.300000,0.278788,0.314861,0.252232,0.049029,0.047651,...,0.047299,0.332500,0.313625,0.046247,0.055431,0.049517,0.035901,0.062483,0.049167,0.280543
cg15812957,0.977235,0.397238,0.964026,0.392934,0.435589,0.939434,0.564567,0.574039,0.975047,0.973772,...,0.976497,0.461237,0.500961,0.963892,0.977533,0.974378,0.979597,0.961994,0.971672,0.619577
cg21825364,0.982263,0.962622,0.983653,0.974200,0.954342,0.973847,0.969880,0.976096,0.979639,0.985340,...,0.981848,0.963953,0.973289,0.969162,0.980127,0.986495,0.985662,0.968560,0.986326,0.977540
cg23654549,0.228583,0.005128,0.005530,0.005386,0.008301,0.008265,0.008326,0.007299,0.162999,0.172470,...,0.152501,0.006958,0.006869,0.066892,0.179412,0.215775,0.136854,0.176094,0.202141,0.006734

In [ ]:
# df_methyl.isnull().sum()
df_methyl.isnull().sum().sum()

0

In [ ]:
# Check for duplicate entries
duplicates = df_methyl.duplicated().sum()
print("Number of duplicate entries: ",duplicates)

Number of duplicate entries:  0

In [ ]:
import matplotlib.pyplot as plt

# Define the individual's dbGaP ID (e.g., 34)
individual_id = '34'

# Extract the data for the specified individual
individual_data = df_methyl[individual_id]

# Get the CpG site names (row names)
cpg_sites = df_methyl.index

# Plot the CpG methylation values for the individual
plt.figure(figsize=(10, 6))
plt.plot(cpg_sites, individual_data, marker='o', linestyle='-')
plt.xlabel('CpG Sites')
plt.ylabel('Methylation Value')
plt.title(f'CpG Methylation Values for Individual {individual_id}')
plt.xticks(rotation=90)
plt.grid(True, axis='y')
plt.show()

In [ ]:
# Plot the CpG methylation values for the individual using a bar plot
plt.figure(figsize=(10, 6))
plt.bar(cpg_sites, individual_data)
plt.xlabel('CpG Sites')
plt.ylabel('Methylation Value')
plt.title(f'CpG Methylation Values for Individual {individual_id}')
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.show()



---

###Subjects DataFrame:

In [ ]:
file_path = "/content/subjects.txt"
df_subjects = pd.read_csv(file_path, sep='\t', index_col=0)
df_subjects

     dbGaP ID        Age sex  Race
ID
1          34  63.000000   M  CAUC
2          35  26.531506   F  CAUC
3          37  51.479452   F    AA
4          39  75.572602   F  CAUC
5          40   0.482191   F    AA
..        ...        ...  ..   ...
104        25  53.956164   M    AA
105        26  45.939726   M    AA
106        27   0.408219   M    AA
107        28  41.578082   M    AA
108        31  30.495890   F    AA

[108 rows x 4 columns]

In [ ]:
df_subjects.isnull().sum()

dbGaP ID    0
Age         0
sex         0
Race        0
dtype: int64

In [ ]:
# Check for duplicate entries
duplicates = df_subjects.duplicated().sum()
print("Number of duplicate entries: ",duplicates)

Number of duplicate entries:  0



---

The relationship between age and methylation can be explored through a correlation analysis or regression analysis, given that we have two DataFrames: df_methyl containing CpG methylation values and df_subjects containing information on individuals, including their age.

In [ ]:
df_methyl.shape

(27578, 108)

In [ ]:
df_methyl_T = df_methyl.T